apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-admin-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: app-admin-api
  template:
    metadata:
      labels:
        app: app-admin-api
    spec:
      containers:
      - name: app-admin-api
        image: registry.gitlab.com/parthakonda/app/app-admin-api:latest
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
        env:
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: postgres
                key: POSTGRES_DB
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: postgres
                key: POSTGRES_USER
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres
                key: POSTGRES_PASSWORD
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: admin-api
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: admin-api
                key: DB_PORT
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: admin-api
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: admin-api
                key: AWS_SECRET_ACCESS_KEY
          - name: FROM_DOMAIN
            valueFrom:
              configMapKeyRef:
                name: admin-api
                key: FROM_DOMAIN
      imagePullSecrets:
        - name: gitlab-registry
