apiVersion: v1
kind: Service
metadata:
  name: app-admin-api-service
spec:
  type: LoadBalancer
  selector:
    app: app-admin-api
  ports:
  - name: admin-api-port
    protocol: TCP
    port: 8000
    targetPort: 8000
