apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-user-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: app-user-api
  template:
    metadata:
      labels:
        app: app-user-api
    spec:
      containers:
      - name: app-user-api
        image: registry.gitlab.com/parthakonda/app/app-user-api:latest
        ports:
        - containerPort: 9001
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: user-api
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: user-api
                key: DB_PORT
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: postgres
                key: POSTGRES_USER
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres
                key: POSTGRES_PASSWORD
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: postgres
                key: POSTGRES_DB
      imagePullSecrets:
        - name: gitlab-registry
