apiVersion: v1
kind: Service
metadata:
  name: app-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: app-frontend
  ports:
  - name: user-ui-port
    protocol: TCP
    port: 80
    targetPort: 80
