apiVersion: v1
kind: Service
metadata:
  name: app-admin-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: app-admin-frontend
  ports:
  - name: admin-ui-port
    protocol: TCP
    port: 80
    targetPort: 80
